# @file    TestRDFAnnotationVCard4.rb
# @brief   fomula units data unit tests
#
# @author  Akiya Jouraku (Ruby conversion)
# @author  Ben Bornstein 
# 
# ====== WARNING ===== WARNING ===== WARNING ===== WARNING ===== WARNING ======
#
# DO NOT EDIT THIS FILE.
#
# This file was generated automatically by converting the file located at
# src/sbml/test/TestRDFAnnotationVCard4.cpp
# using the conversion program dev/utilities/translateTests/translateTests.pl.
# Any changes made here will be lost the next time the file is regenerated.
#
# -----------------------------------------------------------------------------
# This file is part of libSBML.  Please visit http://sbml.org for more
# information about SBML, and the latest version of libSBML.
#
# Copyright 2005-2010 California Institute of Technology.
# Copyright 2002-2005 California Institute of Technology and
#                     Japan Science and Technology Corporation.
# 
# This library is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation.  A copy of the license agreement is provided
# in the file named "LICENSE.txt" included with this software distribution
# and also available online as http://sbml.org/software/libsbml/license.html
# -----------------------------------------------------------------------------
require 'test/unit'
require 'libSBML'

class TestRDFAnnotationVCard4 < Test::Unit::TestCase

  def setup
    filename = "../../sbml/annotation/test/test-data/annotationVcard4.xml"
    filename31 = "../../sbml/annotation/test/test-data/annotationVcard4-l3v1.xml"
    @@d4 = LibSBML::readSBML(filename)
    @@m4 = @@d4.getModel()
    @@d31 = LibSBML::readSBML(filename)
    @@m31 = @@d31.getModel()
    filename = nil
    filename31 = nil
  end

  def teardown
    @@d4 = nil
    @@d31 = nil
  end

  def test_RDFAnnotationV4_getModelHistory
    history = @@m4.getModelHistory()
    assert( history != nil )
    mc = history.getCreator(0)
    assert ((  "Hucka" == mc.getFamilyName() ))
    assert ((  "Mike" == mc.getGivenName() ))
    assert ((  "mhucka@caltech.edu" == mc.getEmail() ))
    assert ((  "BNMC" == mc.getOrganisation() ))
    mc1 = history.getCreator(1)
    assert ((  "Sarah Keating" == mc1.getFamilyName() ))
    assert ((  "Sarah Keating" == mc1.getName() ))
    assert ((  "Sarah Keating" == mc1.getGivenName() ))
    assert ((  "skeating@caltech.edu" == mc1.getEmail() ))
    assert ((  "UH" == mc1.getOrganisation() ))
    date = history.getCreatedDate()
    assert( date.getYear() == 2005 )
    assert( date.getMonth() == 2 )
    assert( date.getDay() == 2 )
    assert( date.getHour() == 14 )
    assert( date.getMinute() == 56 )
    assert( date.getSecond() == 11 )
    assert( date.getSignOffset() == 0 )
    assert( date.getHoursOffset() == 0 )
    assert( date.getMinutesOffset() == 0 )
    assert ((  "2005-02-02T14:56:11Z" == date.getDateAsString() ))
    date = history.getModifiedDate()
    assert( date.getYear() == 2006 )
    assert( date.getMonth() == 5 )
    assert( date.getDay() == 30 )
    assert( date.getHour() == 10 )
    assert( date.getMinute() == 46 )
    assert( date.getSecond() == 2 )
    assert( date.getSignOffset() == 0 )
    assert( date.getHoursOffset() == 0 )
    assert( date.getMinutesOffset() == 0 )
    assert ((  "2006-05-30T10:46:02Z" == date.getDateAsString() ))
    date = history.getModifiedDate(1)
    assert( date.getYear() == 2007 )
    assert( date.getMonth() == 1 )
    assert( date.getDay() == 16 )
    assert( date.getHour() == 15 )
    assert( date.getMinute() == 31 )
    assert( date.getSecond() == 52 )
    assert( date.getSignOffset() == 0 )
    assert( date.getHoursOffset() == 0 )
    assert( date.getMinutesOffset() == 0 )
    assert ((  "2007-01-16T15:31:52Z" == date.getDateAsString() ))
  end

  def test_RDFAnnotationV4_getModelHistory_31
    history = @@m31.getModelHistory()
    assert( history != nil )
    mc = history.getCreator(0)
    assert ((  "Hucka" == mc.getFamilyName() ))
    assert ((  "Mike" == mc.getGivenName() ))
    assert ((  "mhucka@caltech.edu" == mc.getEmail() ))
    assert ((  "BNMC" == mc.getOrganisation() ))
    mc1 = history.getCreator(1)
    assert ((  "Sarah Keating" == mc1.getFamilyName() ))
    assert ((  "Sarah Keating" == mc1.getName() ))
    assert ((  "Sarah Keating" == mc1.getGivenName() ))
    assert ((  "skeating@caltech.edu" == mc1.getEmail() ))
    assert ((  "UH" == mc1.getOrganisation() ))
    date = history.getCreatedDate()
    assert( date.getYear() == 2005 )
    assert( date.getMonth() == 2 )
    assert( date.getDay() == 2 )
    assert( date.getHour() == 14 )
    assert( date.getMinute() == 56 )
    assert( date.getSecond() == 11 )
    assert( date.getSignOffset() == 0 )
    assert( date.getHoursOffset() == 0 )
    assert( date.getMinutesOffset() == 0 )
    assert ((  "2005-02-02T14:56:11Z" == date.getDateAsString() ))
    date = history.getModifiedDate()
    assert( date.getYear() == 2006 )
    assert( date.getMonth() == 5 )
    assert( date.getDay() == 30 )
    assert( date.getHour() == 10 )
    assert( date.getMinute() == 46 )
    assert( date.getSecond() == 2 )
    assert( date.getSignOffset() == 0 )
    assert( date.getHoursOffset() == 0 )
    assert( date.getMinutesOffset() == 0 )
    assert ((  "2006-05-30T10:46:02Z" == date.getDateAsString() ))
    date = history.getModifiedDate(1)
    assert( date.getYear() == 2007 )
    assert( date.getMonth() == 1 )
    assert( date.getDay() == 16 )
    assert( date.getHour() == 15 )
    assert( date.getMinute() == 31 )
    assert( date.getSecond() == 52 )
    assert( date.getSignOffset() == 0 )
    assert( date.getHoursOffset() == 0 )
    assert( date.getMinutesOffset() == 0 )
    assert ((  "2007-01-16T15:31:52Z" == date.getDateAsString() ))
  end

  def test_RDFAnnotationV4_modelWithHistoryAndCVTerms
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setFamilyName("Keating")
    c.setGivenName("Sarah")
    h.addCreator(c)
    d = LibSBML::Date.new(2008,11,17,18,37,0,0,0,0)
    h.setCreatedDate(d)
    h.setModifiedDate(d)
    @@m4.unsetModelHistory()
    @@m4.setModelHistory(h)
    cv = LibSBML::CVTerm.new()
    cv.setQualifierType(LibSBML::BIOLOGICAL_QUALIFIER)
    cv.setBiologicalQualifierType(LibSBML::BQB_IS_VERSION_OF)
    cv.addResource("http://www.geneontology.org/#GO:0005892")
    @@m4.addCVTerm(cv)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m4)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:hasName rdf:parseType=\"Resource\">\n" + 
    "              <vCard4:family-name>Keating</vCard4:family-name>\n" + 
    "              <vCard4:given-name>Sarah</vCard4:given-name>\n" + 
    "            </vCard4:hasName>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2008-11-17T18:37:00Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2008-11-17T18:37:00Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "      <bqbiol:isVersionOf>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:resource=\"http://www.geneontology.org/#GO:0005892\"/>\n" + 
    "        </rdf:Bag>\n" + 
    "      </bqbiol:isVersionOf>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    if (ann != nil)
      assert_equal true, equals(expected,ann.toXMLString())
    end
    end
    c = nil
    d = nil
    h = nil
    cv = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryAndCVTerms_31
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setFamilyName("Keating")
    c.setGivenName("Sarah")
    h.addCreator(c)
    d = LibSBML::Date.new(2008,11,17,18,37,0,0,0,0)
    h.setCreatedDate(d)
    h.setModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    cv = LibSBML::CVTerm.new()
    cv.setQualifierType(LibSBML::BIOLOGICAL_QUALIFIER)
    cv.setBiologicalQualifierType(LibSBML::BQB_IS_VERSION_OF)
    cv.addResource("http://www.geneontology.org/#GO:0005892")
    @@m31.addCVTerm(cv)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:hasName rdf:parseType=\"Resource\">\n" + 
    "              <vCard4:family-name>Keating</vCard4:family-name>\n" + 
    "              <vCard4:given-name>Sarah</vCard4:given-name>\n" + 
    "            </vCard4:hasName>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2008-11-17T18:37:00Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2008-11-17T18:37:00Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "      <bqbiol:isVersionOf>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:resource=\"http://www.geneontology.org/#GO:0005892\"/>\n" + 
    "        </rdf:Bag>\n" + 
    "      </bqbiol:isVersionOf>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    if (ann != nil)
      assert_equal true, equals(expected,ann.toXMLString())
    end
    end
    c = nil
    d = nil
    h = nil
    cv = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryVcard4_1
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setFamilyName("Smith")
    c.setGivenName("John")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    c.setUseSingleName(true)
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:fn>\n" + 
    "              <vCard4:text>John Smith</vCard4:text>\n" + 
    "            </vCard4:fn>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryVcard4_2
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setFamilyName("Smith")
    c.setGivenName("John")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    c.setUseSingleName(false)
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:hasName rdf:parseType=\"Resource\">\n" + 
    "              <vCard4:family-name>Smith</vCard4:family-name>\n" + 
    "              <vCard4:given-name>John</vCard4:given-name>\n" + 
    "            </vCard4:hasName>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryVcard4_3
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setName("John Smith")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    c.setUseSingleName(false)
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:hasName rdf:parseType=\"Resource\">\n" + 
    "              <vCard4:family-name>Smith</vCard4:family-name>\n" + 
    "              <vCard4:given-name>John</vCard4:given-name>\n" + 
    "            </vCard4:hasName>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryVcard4_4
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setName("John Smith")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    c.setUseSingleName(true)
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:fn>\n" + 
    "              <vCard4:text>John Smith</vCard4:text>\n" + 
    "            </vCard4:fn>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryWithCharacterReference
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setFamilyName("Dr&#228;ger")
    c.setGivenName("Andreas")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m4.unsetModelHistory()
    @@m4.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m4)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:hasName rdf:parseType=\"Resource\">\n" + 
    "              <vCard4:family-name>Dr&#228;ger</vCard4:family-name>\n" + 
    "              <vCard4:given-name>Andreas</vCard4:given-name>\n" + 
    "            </vCard4:hasName>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryWithCharacterReference_31
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setFamilyName("Dr&#228;ger")
    c.setGivenName("Andreas")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:hasName rdf:parseType=\"Resource\">\n" + 
    "              <vCard4:family-name>Dr&#228;ger</vCard4:family-name>\n" + 
    "              <vCard4:given-name>Andreas</vCard4:given-name>\n" + 
    "            </vCard4:hasName>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryWithOneName
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setName("John Smith")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m4.unsetModelHistory()
    @@m4.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m4)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:fn>\n" + 
    "              <vCard4:text>John Smith</vCard4:text>\n" + 
    "            </vCard4:fn>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

  def test_RDFAnnotationV4_modelWithHistoryWithOneName_31
    h = LibSBML::ModelHistory.new()
    c = LibSBML::ModelCreator.new()
    c.setName("John Smith")
    c.setEmail("a@bcd")
    c.setOrganization("UT")
    h.addCreator(c)
    d = LibSBML::Date.new(2005,2,2,14,56,11)
    h.setCreatedDate(d)
    h.addModifiedDate(d)
    @@m31.unsetModelHistory()
    @@m31.setModelHistory(h)
    ann = LibSBML::RDFAnnotationParser.parseModelHistory(@@m31)
    expected = "<annotation>\n" + 
    "  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:vCard4=\"http://www.w3.org/2006/vcard/ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n" + 
    "    <rdf:Description rdf:about=\"#_000001\">\n" + 
    "      <dcterms:creator>\n" + 
    "        <rdf:Bag>\n" + 
    "          <rdf:li rdf:parseType=\"Resource\">\n" + 
    "            <vCard4:fn>\n" + 
    "              <vCard4:text>John Smith</vCard4:text>\n" + 
    "            </vCard4:fn>\n" + 
    "            <vCard4:hasEmail>a@bcd</vCard4:hasEmail>\n" + 
    "            <vCard4:organization-name>UT</vCard4:organization-name>\n" + 
    "          </rdf:li>\n" + 
    "        </rdf:Bag>\n" + 
    "      </dcterms:creator>\n" + 
    "      <dcterms:created rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:created>\n" + 
    "      <dcterms:modified rdf:parseType=\"Resource\">\n" + 
    "        <dcterms:W3CDTF>2005-02-02T14:56:11Z</dcterms:W3CDTF>\n" + 
    "      </dcterms:modified>\n" + 
    "    </rdf:Description>\n" + 
    "  </rdf:RDF>\n" + 
    "</annotation>"
    assert_equal true, equals(expected,ann.toXMLString())
    c = nil
    d = nil
    h = nil
    ann = nil
  end

end
