# @file    TestRenameIDs.rb
# @brief   RenameIDs unit tests
#
# @author  Akiya Jouraku (Ruby conversion)
# @author  Lucian Smith 
# 
# ====== WARNING ===== WARNING ===== WARNING ===== WARNING ===== WARNING ======
#
# DO NOT EDIT THIS FILE.
#
# This file was generated automatically by converting the file located at
# src/sbml/test/TestRenameIDs.cpp
# using the conversion program dev/utilities/translateTests/translateTests.pl.
# Any changes made here will be lost the next time the file is regenerated.
#
# -----------------------------------------------------------------------------
# This file is part of libSBML.  Please visit http://sbml.org for more
# information about SBML, and the latest version of libSBML.
#
# Copyright 2005-2010 California Institute of Technology.
# Copyright 2002-2005 California Institute of Technology and
#                     Japan Science and Technology Corporation.
# 
# This library is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation.  A copy of the license agreement is provided
# in the file named "LICENSE.txt" included with this software distribution
# and also available online as http://sbml.org/software/libsbml/license.html
# -----------------------------------------------------------------------------
require 'test/unit'
require 'libSBML'

class TestRenameIDs < Test::Unit::TestCase

  def test_RenameIDs
    reader = LibSBML::SBMLReader.new()
    filename = "../../sbml/sbml/test/test-data/"
    filename += "multiple-ids.xml"
    d = reader.readSBML(filename)
    if (d == NULL || d.getModel() == nil)
    end
    allElements = d.getAllElements()
    assert( obj != nil )
    obj.renameSIdRefs("comp", "comp_new")
    obj.renameSIdRefs("C", "C_new")
    obj.renameSIdRefs("conv", "conv_new")
    obj.renameSIdRefs("b", "b_new")
    obj.renameSIdRefs("b2", "b2_new")
    obj.renameSIdRefs("x", "x_new")
    obj.renameSIdRefs("y"_COMMA_ "y_new"); //The 'y' here in the function definition not actually an SIdso this should have no effect.obj.renameUnitSIdRefs("volume"_COMMA_ "volume_new")
    obj.renameUnitSIdRefs("substance", "substance_new")
    obj.renameUnitSIdRefs("item", "item_new")
    obj.renameUnitSIdRefs("second", "second_new")
    obj.renameUnitSIdRefs("litre", "litre_new")
    obj.renameUnitSIdRefs("candela", "candela_new")
    obj.renameUnitSIdRefs("farad", "farad_new")
    obj.renameUnitSIdRefs("coulomb", "coulomb_new")
  end
  obj = d.getElementByMetaId("meta21")
  assert( obj != nil )
  xml = obj.toSBML()
  assert( xmlstr.find("y_new") == string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  obj = d.getElementByMetaId("meta4")
  assert( obj != nil )
  compartment = obj
  assert( compartment.getUnits() ==  "volume_new" )
  obj = d.getElementByMetaId("meta6")
  assert( obj != nil )
  sp = obj
  assert( sp.getSubstanceUnits() ==  "substance_new" )
  assert( sp.getConversionFactor() ==  "conv_new" )
  assert( sp.getCompartment() ==  "comp_new" )
  obj = d.getElementByMetaId("meta11")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("x_new") == string::npos )
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("b2_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  obj = d.getElementByMetaId("meta28")
  assert( obj != nil )
  lp = obj
  assert( lp.getUnits() ==  "volume_new" )
  obj = d.getElementByMetaId("meta10")
  assert( obj != nil )
  sr = obj
  assert( sr.getSpecies() ==  "b_new" )
  obj = d.getElementByMetaId("meta10")
  assert( obj != nil )
  msr = obj
  assert( msr.getSpecies() ==  "b_new" )
  obj = d.getElementByMetaId("meta8")
  assert( obj != nil )
  rxn = obj
  assert( rxn.getCompartment() ==  "comp_new" )
  obj = d.getElementByMetaId("meta18")
  assert( obj != nil )
  p = obj
  assert( p.getUnits() ==  "volume_new" )
  obj = d.getElementByMetaId("meta14")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  obj = d.getElementByMetaId("meta16")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  ea = obj
  assert( ea.getVariable() ==  "b_new" )
  obj = d.getElementByMetaId("meta17")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  obj = d.getElementByMetaId("meta19")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  obj = d.getElementByMetaId("meta23")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("x_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  ia = obj
  assert( ia.getSymbol() ==  "b_new" )
  obj = d.getElementByMetaId("meta25")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  rr = obj
  assert( rr.getVariable() ==  "x_new" )
  obj = d.getElementByMetaId("meta26")
  assert( obj != nil )
  xml = obj.toSBML()
  xmlstr = xml
  assert( xmlstr.find("b_new") != string::npos )
  assert( xmlstr.find("volume_new") != string::npos )
  ar = obj
  assert( ar.getVariable() ==  "C_new" )
  obj = d.getElementByMetaId("meta2")
  assert( obj != nil )
  mod = obj
  assert( mod.getConversionFactor() ==  "conv_new" )
  assert( mod.getSubstanceUnits() ==  "item_new" )
  assert( mod.getTimeUnits() ==  "second_new" )
  assert( mod.getVolumeUnits() ==  "litre_new" )
  assert( mod.getAreaUnits() ==  "candela_new" )
  assert( mod.getLengthUnits() ==  "farad_new" )
  assert( mod.getExtentUnits() ==  "coulomb_new" )
  d = nil
  allElements = nil
end

end
