# @file    TestSBMLConvertFromL3V2.rb
# @brief   SBMLConvert unit tests for strict conversion from L3V2
#
# @author  Akiya Jouraku (Ruby conversion)
# @author  Sarah Keating 
# 
# ====== WARNING ===== WARNING ===== WARNING ===== WARNING ===== WARNING ======
#
# DO NOT EDIT THIS FILE.
#
# This file was generated automatically by converting the file located at
# src/sbml/test/TestSBMLConvertFromL3V2.cpp
# using the conversion program dev/utilities/translateTests/translateTests.pl.
# Any changes made here will be lost the next time the file is regenerated.
#
# -----------------------------------------------------------------------------
# This file is part of libSBML.  Please visit http://sbml.org for more
# information about SBML, and the latest version of libSBML.
#
# Copyright 2005-2010 California Institute of Technology.
# Copyright 2002-2005 California Institute of Technology and
#                     Japan Science and Technology Corporation.
# 
# This library is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation.  A copy of the license agreement is provided
# in the file named "LICENSE.txt" included with this software distribution
# and also available online as http://sbml.org/software/libsbml/license.html
# -----------------------------------------------------------------------------
require 'test/unit'
require 'libSBML'

class TestSBMLConvertFromL3V2 < Test::Unit::TestCase

  def test_SBMLConvertFromL3V2_convertEmptyLO_nonstrict
    expected = "<model>\n" + 
    "  <listOfParameters>\n" + 
    "    <annotation>some annotation</annotation>\n" + 
    "  </listOfParameters>\n" + 
    "</model>"
    expected1 = + "<model/>"
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    lo = m.getListOfParameters()
    lo.setAnnotation("some annotation")
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( lo.getLevel() == 3 )
    assert( lo.getVersion() == 2 )
    assert( lo.isSetAnnotation() == true )
    sbml = m.toSBML()
    assert_equal true, equals(expected,sbml)
    sbml = nil
    done = doc.setLevelAndVersion(2,4,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(EmptyListOfElementNotSupported) == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getListOfParameters().getLevel() == 2 )
    assert( doc.getModel().getListOfParameters().getVersion() == 4 )
    m1 = doc.getModel()
    sbml = m1.toSBML()
    assert_equal true, equals(expected1,sbml)
    sbml = nil
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertEmptyLO_strict
    expected = "<model>\n" + 
    "  <listOfParameters>\n" + 
    "    <annotation>some annotation</annotation>\n" + 
    "  </listOfParameters>\n" + 
    "</model>"
    expected1 = + "<model/>"
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    lo = m.getListOfParameters()
    lo.setAnnotation("some annotation")
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( lo.getLevel() == 3 )
    assert( lo.getVersion() == 2 )
    assert( lo.isSetAnnotation() == true )
    sbml = m.toSBML()
    assert_equal true, equals(expected,sbml)
    sbml = nil
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(EmptyListOfElementNotSupported) == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getListOfParameters().getLevel() == 2 )
    assert( doc.getModel().getListOfParameters().getVersion() == 4 )
    m1 = doc.getModel()
    sbml = m1.toSBML()
    assert_equal true, equals(expected1,sbml)
    sbml = nil
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIA_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "2*3";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == false )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,4,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(ConvertibleMathInitialAssignment) == false )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 4 )
    assert( m.getNumInitialAssignments() == 1 )
    node1 = doc.getModel().getInitialAssignment(0).getMath()
    str = node1.formulaToL3String()
    assert ((  "2 * 3" == str ))
    assert( doc.getModel().getParameter(0).isSetValue() == false )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIA_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "2*3";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == false )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(ConvertibleMathInitialAssignment) == false )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 4 )
    assert( m.getNumInitialAssignments() == 1 )
    node1 = doc.getModel().getInitialAssignment(0).getMath()
    str = node1.formulaToL3String()
    assert ((  "2 * 3" == str ))
    assert( doc.getModel().getParameter(0).isSetValue() == false )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIAnewMath1_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    p1 = m.createParameter()
    p1.setId("x")
    p1.setConstant(true)
    p1.setValue(1)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "rateOf(x)";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == true )
    assert( ar.getMath().usesRateOf() == true )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,4,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(MathMLElementNotSupported) == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 4 )
    assert( m.getNumInitialAssignments() == 1 )
    assert( doc.getModel().getParameter(0).isSetValue() == false )
    node1 = doc.getModel().getInitialAssignment(0).getMath()
    str = node1.formulaToL3String()
    assert ((  "rateOf(x)" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIAnewMath1_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    p1 = m.createParameter()
    p1.setId("x")
    p1.setConstant(true)
    p1.setValue(1)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "rateOf(x)";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == true )
    assert( ar.getMath().usesRateOf() == true )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == false )
    assert( doc.getErrorLog().contains(MathMLElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( doc.getModel().getParameter(0).getLevel() == 3 )
    assert( doc.getModel().getParameter(0).getVersion() == 2 )
    assert( m.getNumInitialAssignments() == 1 )
    assert( doc.getModel().getParameter(0).isSetValue() == false )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIAnewMath_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "min(2, 3)";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == true )
    assert( ar.getMath().usesRateOf() == false )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(ConvertibleMathInitialAssignment) == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 4 )
    assert( m.getNumInitialAssignments() == 0 )
    assert( doc.getModel().getParameter(0).isSetValue() == true )
    assert_equal true, util_isEqual
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIAnewMath_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "min(2, 3)";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == true )
    assert( ar.getMath().usesRateOf() == false )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(ConvertibleMathInitialAssignment) == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 4 )
    assert( m.getNumInitialAssignments() == 0 )
    assert( doc.getModel().getParameter(0).isSetValue() == true )
    assert_equal true, util_isEqual
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIAvalue_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "2 * 3";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == false )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,1,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(ConvertibleMathInitialAssignment) == false )
    assert( doc.getErrorLog().contains(MathMLElementNotSupported) == false )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 1 )
    assert( m.getNumInitialAssignments() == 0 )
    assert( doc.getModel().getParameter(0).isSetValue() == true )
    assert_equal true, util_isEqual
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertIAvalue_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createInitialAssignment()
    ar.setSymbol("p")
    math =  "2 * 3";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == false )
    assert( m.getNumInitialAssignments() == 1 )
    assert( p.isSetValue() == false )
    done = doc.setLevelAndVersion(2,1,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(ConvertibleMathInitialAssignment) == false )
    assert( doc.getErrorLog().contains(MathMLElementNotSupported) == false )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getParameter(0).getLevel() == 2 )
    assert( doc.getModel().getParameter(0).getVersion() == 1 )
    assert( m.getNumInitialAssignments() == 0 )
    assert( doc.getModel().getParameter(0).isSetValue() == true )
    assert_equal true, util_isEqual
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingEAMath_bug
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    e = m.createEvent()
    e.setUseValuesFromTriggerTime(true)
    t = e.createTrigger()
    t.setPersistent(false)
    t.setInitialValue(false)
    math =  "true";
    node = .parseL3Formula()
    t.setMath(node)
    node = nil
    ea = e.createEventAssignment()
    ea.setVariable("p")
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( e.getLevel() == 3 )
    assert( e.getVersion() == 2 )
    assert( e.isSetTrigger() == true )
    assert( e.getTrigger().isSetMath() == true )
    assert( e.getNumEventAssignments() == 1 )
    assert( e.getEventAssignment(0).isSetMath() == false )
    done = doc.setLevelAndVersion(3,1,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingMathElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getEvent(0).getLevel() == 3 )
    assert( doc.getModel().getEvent(0).getVersion() == 1 )
    assert( doc.getModel().getEvent(0).isSetTrigger() == true )
    assert( doc.getModel().getEvent(0).getTrigger().isSetMath() == true )
    assert( e.getNumEventAssignments() == 0 )
    node1 = doc.getModel().getEvent(0).getTrigger().getMath()
    str = node1.formulaToL3String()
    assert ((  "true" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingFast
    filename = "../../sbml/sbml/test/test-data/"
    filename += "l3v2-reaction.xml"
    doc = LibSBML::readSBML()
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( doc.getModel().getNumReactions() == 1 )
    r = doc.getModel().getReaction(0)
    assert( r != nil )
    assert( r.isSetFast() == false )
    done = doc.setLevelAndVersion(3,1,true)
    assert( done == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    r = doc.getModel().getReaction(0)
    assert( r != nil )
    assert( r.isSetFast() == true )
    assert( r.getFast() == false )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingMathForStoich_strict
    filename = "../../sbml/sbml/test/test-data/"
    filename += "l3v2-stoich-math-missing.xml"
    doc = LibSBML::readSBML()
    m = doc.getModel()
    ar = m.getRule(0)
    sr = m.getReaction(0).getProduct(0)
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == false )
    assert( m.getNumRules() == 1 )
    assert( ar.getVariable() == sr.getId() )
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    m = doc.getModel()
    assert( m.getNumRules() == 0 )
    sr = m.getReaction(0).getProduct(0)
    assert( sr.isSetStoichiometryMath() == false )
    assert( sr.isSetStoichiometry() == true )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingMath_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createAssignmentRule()
    ar.setVariable("p")
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == false )
    assert( m.getNumRules() == 1 )
    done = doc.setLevelAndVersion(3,1,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingMathElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getParameter(0).getLevel() == 3 )
    assert( doc.getModel().getParameter(0).getVersion() == 1 )
    assert( m.getNumRules() == 1 )
    ar = doc.getModel().getAssignmentRule("p")
    assert( ar.isSetMath() == false )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingMath_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createAssignmentRule()
    ar.setVariable("p")
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == false )
    assert( m.getNumRules() == 1 )
    done = doc.setLevelAndVersion(3,1,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingMathElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getParameter(0).getLevel() == 3 )
    assert( doc.getModel().getParameter(0).getVersion() == 1 )
    assert( m.getNumRules() == 0 )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingReactantProducts_nonstrict
    filename = "../../sbml/sbml/test/test-data/"
    filename += "l3v2-reaction-no-sr.xml"
    doc = LibSBML::readSBML()
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( doc.getModel().getNumReactions() == 1 )
    r = doc.getModel().getReaction(0)
    assert( r != nil )
    assert( r.getNumProducts() == 0 )
    assert( r.getNumReactants() == 0 )
    assert( r.getNumModifiers() == 0 )
    assert( r.isSetKineticLaw() == true )
    done = doc.setLevelAndVersion(3,1,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingParticipantsNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getNumReactions() == 1 )
    r = doc.getModel().getReaction(0)
    assert( r != nil )
    assert( r.getNumProducts() == 0 )
    assert( r.getNumReactants() == 0 )
    assert( r.getNumModifiers() == 0 )
    assert( r.isSetKineticLaw() == true )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingReactantProducts_strict
    filename = "../../sbml/sbml/test/test-data/"
    filename += "l3v2-reaction-no-sr.xml"
    doc = LibSBML::readSBML()
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( doc.getModel().getNumReactions() == 1 )
    r = doc.getModel().getReaction(0)
    assert( r != nil )
    assert( r.getNumProducts() == 0 )
    assert( r.getNumReactants() == 0 )
    assert( r.getNumModifiers() == 0 )
    assert( r.isSetKineticLaw() == true )
    done = doc.setLevelAndVersion(3,1,true)
    assert( done == false )
    assert( doc.getErrorLog().contains(MissingParticipantsNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( doc.getModel().getNumReactions() == 1 )
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingTriggerMath_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    e = m.createEvent()
    e.setUseValuesFromTriggerTime(true)
    t = e.createTrigger()
    t.setPersistent(false)
    t.setInitialValue(false)
    ea = e.createEventAssignment()
    ea.setVariable("p")
    math =  "2";
    node = .parseL3Formula()
    ea.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( e.getLevel() == 3 )
    assert( e.getVersion() == 2 )
    assert( e.isSetTrigger() == true )
    assert( e.getTrigger().isSetMath() == false )
    done = doc.setLevelAndVersion(3,1,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingMathElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getEvent(0).getLevel() == 3 )
    assert( doc.getModel().getEvent(0).getVersion() == 1 )
    assert( doc.getModel().getEvent(0).isSetTrigger() == true )
    assert( doc.getModel().getEvent(0).getTrigger().isSetMath() == true )
    node1 = doc.getModel().getEvent(0).getTrigger().getMath()
    str = node1.formulaToL3String()
    assert ((  "false" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingTriggerMath_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    e = m.createEvent()
    e.setUseValuesFromTriggerTime(true)
    t = e.createTrigger()
    t.setPersistent(false)
    t.setInitialValue(false)
    ea = e.createEventAssignment()
    ea.setVariable("p")
    math =  "2";
    node = .parseL3Formula()
    ea.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( e.getLevel() == 3 )
    assert( e.getVersion() == 2 )
    assert( e.isSetTrigger() == true )
    assert( e.getTrigger().isSetMath() == false )
    done = doc.setLevelAndVersion(3,1,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingMathElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getEvent(0).getLevel() == 3 )
    assert( doc.getModel().getEvent(0).getVersion() == 1 )
    assert( doc.getModel().getEvent(0).isSetTrigger() == true )
    assert( doc.getModel().getEvent(0).getTrigger().isSetMath() == true )
    node1 = doc.getModel().getEvent(0).getTrigger().getMath()
    str = node1.formulaToL3String()
    assert ((  "false" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingTrigger_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    e = m.createEvent()
    e.setUseValuesFromTriggerTime(true)
    ea = e.createEventAssignment()
    ea.setVariable("p")
    math =  "2";
    node = .parseL3Formula()
    ea.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( e.getLevel() == 3 )
    assert( e.getVersion() == 2 )
    assert( e.isSetTrigger() == false )
    done = doc.setLevelAndVersion(3,1,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingTriggerElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getEvent(0).getLevel() == 3 )
    assert( doc.getModel().getEvent(0).getVersion() == 1 )
    assert( doc.getModel().getEvent(0).isSetTrigger() == true )
    assert( doc.getModel().getEvent(0).getTrigger().isSetMath() == true )
    node1 = doc.getModel().getEvent(0).getTrigger().getMath()
    str = node1.formulaToL3String()
    assert ((  "false" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertMissingTrigger_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    e = m.createEvent()
    e.setUseValuesFromTriggerTime(true)
    ea = e.createEventAssignment()
    ea.setVariable("p")
    math =  "2";
    node = .parseL3Formula()
    ea.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( e.getLevel() == 3 )
    assert( e.getVersion() == 2 )
    assert( e.isSetTrigger() == false )
    done = doc.setLevelAndVersion(3,1,true)
    assert( done == true )
    assert( doc.getErrorLog().contains(MissingTriggerElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 1 )
    assert( doc.getModel().getEvent(0).getLevel() == 3 )
    assert( doc.getModel().getEvent(0).getVersion() == 1 )
    assert( doc.getModel().getEvent(0).isSetTrigger() == true )
    assert( doc.getModel().getEvent(0).getTrigger().isSetMath() == true )
    node1 = doc.getModel().getEvent(0).getTrigger().getMath()
    str = node1.formulaToL3String()
    assert ((  "false" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertnewMath_nonstrict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createAssignmentRule()
    ar.setVariable("p")
    math =  "min(2, 3)";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == true )
    done = doc.setLevelAndVersion(2,4,false)
    assert( done == true )
    assert( doc.getErrorLog().contains(MathMLElementNotSupported) == true )
    assert( doc.getLevel() == 2 )
    assert( doc.getVersion() == 4 )
    assert( doc.getModel().getRule(0).getLevel() == 2 )
    assert( doc.getModel().getRule(0).getVersion() == 4 )
    assert( doc.getModel().getRule(0).isSetMath() == true )
    assert( doc.getModel().getRule(0).getMath().usesL3V2MathConstructs() == true )
    node1 = doc.getModel().getRule(0).getMath()
    str = node1.formulaToL3String()
    assert ((  "min(2, 3)" == str ))
    doc = nil
  end

  def test_SBMLConvertFromL3V2_convertnewMath_strict
    doc = LibSBML::SBMLDocument.new(3,2)
    m = doc.createModel()
    p = m.createParameter()
    p.setId("p")
    p.setConstant(false)
    ar = m.createAssignmentRule()
    ar.setVariable("p")
    math =  "min(2, 3)";
    node = .parseL3Formula()
    ar.setMath(node)
    node = nil
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( ar.getLevel() == 3 )
    assert( ar.getVersion() == 2 )
    assert( ar.isSetMath() == true )
    assert( ar.getMath().usesL3V2MathConstructs() == true )
    done = doc.setLevelAndVersion(2,4,true)
    assert( done == false )
    assert( doc.getErrorLog().contains(MathMLElementNotSupported) == true )
    assert( doc.getLevel() == 3 )
    assert( doc.getVersion() == 2 )
    assert( doc.getModel().getRule(0).getLevel() == 3 )
    assert( doc.getModel().getRule(0).getVersion() == 2 )
    assert( doc.getModel().getRule(0).isSetMath() == true )
    assert( doc.getModel().getRule(0).getMath().usesL3V2MathConstructs() == true )
    node1 = doc.getModel().getRule(0).getMath()
    str = node1.formulaToL3String()
    assert ((  "min(2, 3)" == str ))
    doc = nil
  end

end
