/*
 * @file    TestLevelCompatibility.java
 * @brief   Compatability between levels unit tests
 *
 * @author  Akiya Jouraku (Java conversion)
 * @author  Sarah Keating 
 * 
 * ====== WARNING ===== WARNING ===== WARNING ===== WARNING ===== WARNING ======
 *
 * DO NOT EDIT THIS FILE.
 *
 * This file was generated automatically by converting the file located at
 * src/sbml/test/TestLevelCompatibility.cpp
 * using the conversion program dev/utilities/translateTests/translateTests.pl.
 * Any changes made here will be lost the next time the file is regenerated.
 *
 * -----------------------------------------------------------------------------
 * This file is part of libSBML.  Please visit http://sbml.org for more
 * information about SBML, and the latest version of libSBML.
 *
 * Copyright 2005-2010 California Institute of Technology.
 * Copyright 2002-2005 California Institute of Technology and
 *                     Japan Science and Technology Corporation.
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation.  A copy of the license agreement is provided
 * in the file named "LICENSE.txt" included with this software distribution
 * and also available online as http://sbml.org/software/libsbml/license.html
 * -----------------------------------------------------------------------------
 */

package org.sbml.libsbml.test.sbml;

import org.sbml.libsbml.*;

import java.io.File;
import java.lang.AssertionError;

public class TestLevelCompatibility {

  static void assertTrue(boolean condition) throws AssertionError
  {
    if (condition == true)
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertEquals(Object a, Object b) throws AssertionError
  {
    if ( (a == null) && (b == null) )
    {
      return;
    }
    else if ( (a == null) || (b == null) )
    {
      throw new AssertionError();
    }
    else if (a.equals(b))
    {
      return;
    }

    throw new AssertionError();
  }

  static void assertNotEquals(Object a, Object b) throws AssertionError
  {
    if ( (a == null) && (b == null) )
    {
      throw new AssertionError();
    }
    else if ( (a == null) || (b == null) )
    {
      return;
    }
    else if (a.equals(b))
    {
      throw new AssertionError();
    }
  }

  static void assertEquals(boolean a, boolean b) throws AssertionError
  {
    if ( a == b )
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertNotEquals(boolean a, boolean b) throws AssertionError
  {
    if ( a != b )
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertEquals(int a, int b) throws AssertionError
  {
    if ( a == b )
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertNotEquals(int a, int b) throws AssertionError
  {
    if ( a != b )
    {
      return;
    }
    throw new AssertionError();
  }

  public void test_LevelCompatibility_unit_fails()
  {
    SBMLReader reader = new SBMLReader();
    SBMLDocument d;
    String filename = new String( "../../sbml/sbml/test/test-data/" );
    filename += "inconsistent-l2v1-units.xml";
    d = reader.readSBML(filename);
    if (d == null);
    {
    }
    long n = d.checkL2v1Compatibility();
    assertTrue( n == 1 );
    assertTrue( d.getError(0).getErrorId().equals(StrictUnitsRequiredInL2v1) );
    d.getErrorLog().clearLog();
    n = d.checkL2v1Compatibility(true);
    assertTrue( n == 0 );
    d = null;
  }

  public void test_LevelCompatibility_unit_fails_l1()
  {
    SBMLReader reader = new SBMLReader();
    SBMLDocument d;
    String filename = new String( "../../sbml/sbml/test/test-data/" );
    filename += "inconsistent-l2v1-units.xml";
    d = reader.readSBML(filename);
    if (d == null);
    {
    }
    long n = d.checkL1Compatibility();
    assertTrue( n == 1 );
    assertTrue( d.getError(0).getErrorId().equals(StrictUnitsRequiredInL1) );
    d.getErrorLog().clearLog();
    n = d.checkL1Compatibility(true);
    assertTrue( n == 0 );
    d = null;
  }

  public void test_LevelCompatibility_unit_fails_l2v2()
  {
    SBMLReader reader = new SBMLReader();
    SBMLDocument d;
    String filename = new String( "../../sbml/sbml/test/test-data/" );
    filename += "inconsistent-l2v1-units.xml";
    d = reader.readSBML(filename);
    if (d == null);
    {
    }
    long n = d.checkL2v2Compatibility();
    assertTrue( n == 1 );
    assertTrue( d.getError(0).getErrorId().equals(StrictUnitsRequiredInL2v2) );
    d.getErrorLog().clearLog();
    n = d.checkL1Compatibility(true);
    assertTrue( n == 0 );
    d = null;
  }

  public void test_LevelCompatibility_unit_fails_l2v3()
  {
    SBMLReader reader = new SBMLReader();
    SBMLDocument d;
    String filename = new String( "../../sbml/sbml/test/test-data/" );
    filename += "inconsistent-l2v1-units.xml";
    d = reader.readSBML(filename);
    if (d == null);
    {
    }
    long n = d.checkL2v3Compatibility();
    assertTrue( n == 1 );
    assertTrue( d.getError(0).getErrorId().equals(StrictUnitsRequiredInL2v3) );
    d.getErrorLog().clearLog();
    n = d.checkL1Compatibility(true);
    assertTrue( n == 0 );
    d = null;
  }

  public void test_LevelCompatibility_unit_warnings()
  {
    SBMLReader reader = new SBMLReader();
    SBMLDocument d;
    String filename = new String( "../../sbml/sbml/test/test-data/" );
    filename += "inconsistent-l2v1-units-2.xml";
    d = reader.readSBML(filename);
    if (d == null);
    {
    }
    long n = d.checkL2v1Compatibility();
    assertTrue( n == 0 );
    d.getErrorLog().clearLog();
    n = d.checkL2v1Compatibility(true);
    assertTrue( n == 0 );
    d = null;
  }

  public void test_LevelCompatibility_unit_warnings_l1()
  {
    SBMLReader reader = new SBMLReader();
    SBMLDocument d;
    String filename = new String( "../../sbml/sbml/test/test-data/" );
    filename += "inconsistent-l2v1-units-2.xml";
    d = reader.readSBML(filename);
    if (d == null);
    {
    }
    long n = d.checkL1Compatibility();
    assertTrue( n == 0 );
    d.getErrorLog().clearLog();
    n = d.checkL1Compatibility(true);
    assertTrue( n == 0 );
    d = null;
  }

  /**
   * Loads the SWIG-generated libSBML Java module when this class is
   * loaded, or reports a sensible diagnostic message about why it failed.
   */
  static
  {
    String varname;
    String shlibname;

    if (System.getProperty("mrj.version") != null)
    {
      varname = "DYLD_LIBRARY_PATH";    // We're on a Mac.
      shlibname = "libsbmlj.jnilib and/or libsbml.dylib";
    }
    else
    {
      varname = "LD_LIBRARY_PATH";      // We're not on a Mac.
      shlibname = "libsbmlj.so and/or libsbml.so";
    }

    try
    {
      System.loadLibrary("sbmlj");
      // For extra safety, check that the jar file is in the classpath.
      Class.forName("org.sbml.libsbml.libsbml");
    }
    catch (SecurityException e)
    {
      e.printStackTrace();
      System.err.println("Could not load the libSBML library files due to a"+
                         " security exception.\n");
      System.exit(1);
    }
    catch (UnsatisfiedLinkError e)
    {
      e.printStackTrace();
      System.err.println("Error: could not link with the libSBML library files."+
                         " It is likely\nyour " + varname +
                         " environment variable does not include the directories\n"+
                         "containing the " + shlibname + " library files.\n");
      System.exit(1);
    }
    catch (ClassNotFoundException e)
    {
      e.printStackTrace();
      System.err.println("Error: unable to load the file libsbmlj.jar."+
                         " It is likely\nyour -classpath option and CLASSPATH" +
                         " environment variable\n"+
                         "do not include the path to libsbmlj.jar.\n");
      System.exit(1);
    }
  }
}
