///  @file    TestSBMLValidators.cs
///  @brief   unit tests for SBMLValidator, SBMLInternalValidator and SBMLExternalValidator
///  @author  Frank Bergmann (Csharp conversion)
///  @author  Akiya Jouraku (Csharp conversion)
///  @author  Frank Bergmann 
///  
///  ====== WARNING ===== WARNING ===== WARNING ===== WARNING ===== WARNING ======
/// 
///  DO NOT EDIT THIS FILE.
/// 
///  This file was generated automatically by converting the file located at
///  src/sbml/test/TestSBMLValidators.cpp
///  using the conversion program dev/utilities/translateTests/translateTests.pl.
///  Any changes made here will be lost the next time the file is regenerated.
/// 
///  -----------------------------------------------------------------------------
///  This file is part of libSBML.  Please visit http://sbml.org for more
///  information about SBML, and the latest version of libSBML.
/// 
///  Copyright 2005-2010 California Institute of Technology.
///  Copyright 2002-2005 California Institute of Technology and
///                      Japan Science and Technology Corporation.
///  
///  This library is free software; you can redistribute it and/or modify it
///  under the terms of the GNU Lesser General Public License as published by
///  the Free Software Foundation.  A copy of the license agreement is provided
///  in the file named "LICENSE.txt" included with this software distribution
///  and also available online as http://sbml.org/software/libsbml/license.html
///  -----------------------------------------------------------------------------


namespace LibSBMLCSTest.sbml {

  using libsbmlcs;

  using System;

  using System.IO;

  public class TestSBMLValidators {
    public class AssertionError : System.Exception 
    {
      public AssertionError() : base()
      {
        
      }
    }


    static void assertTrue(bool condition)
    {
      if (condition == true)
      {
        return;
      }
      throw new AssertionError();
    }

    static void assertEquals(object a, object b)
    {
      if ( (a == null) && (b == null) )
      {
        return;
      }
      else if ( (a == null) || (b == null) )
      {
        throw new AssertionError();
      }
      else if (a.Equals(b))
      {
        return;
      }
  
      throw new AssertionError();
    }

    static void assertNotEquals(object a, object b)
    {
      if ( (a == null) && (b == null) )
      {
        throw new AssertionError();
      }
      else if ( (a == null) || (b == null) )
      {
        return;
      }
      else if (a.Equals(b))
      {
        throw new AssertionError();
      }
    }

    static void assertEquals(bool a, bool b)
    {
      if ( a == b )
      {
        return;
      }
      throw new AssertionError();
    }

    static void assertNotEquals(bool a, bool b)
    {
      if ( a != b )
      {
        return;
      }
      throw new AssertionError();
    }

    static void assertEquals(int a, int b)
    {
      if ( a == b )
      {
        return;
      }
      throw new AssertionError();
    }

    static void assertNotEquals(int a, int b)
    {
      if ( a != b )
      {
        return;
      }
      throw new AssertionError();
    }


    public void test_SBMLValidators_create()
    {
      SBMLValidator validator;
      validator.setDocument(null);
      assertTrue( validator.getDocument() == null );
      assertTrue( validator.getModel() == null );
      assertTrue( validator.getErrorLog() == null );
      assertTrue( validator.getFailures().size() == 0 );
      validator.logFailure(new SBMLError());
      assertTrue( validator.getFailures().size() == 1 );
      validator.clearFailures();
      SBMLDocument doc = new SBMLDocument();
      doc.createModel();
      validator.setDocument(doc);
      assertTrue( validator.getDocument() != null );
      assertTrue( validator.getModel() != null );
      assertTrue( validator.getErrorLog() != null );
      assertTrue( validator.getFailures().size() == 0 );
      assertTrue( validator.validate() == 0 );
    }

    public void test_SBMLValidators_internal()
    {
      SBMLInternalValidator validator;
      validator.setDocument(null);
      assertTrue( validator.getDocument() == null );
      assertTrue( validator.getModel() == null );
      assertTrue( validator.getErrorLog() == null );
      assertTrue( validator.getFailures().size() == 0 );
      validator.logFailure(new SBMLError());
      assertTrue( validator.getFailures().size() == 1 );
      validator.clearFailures();
      SBMLDocument doc = new SBMLDocument();
      doc.createModel();
      validator.setDocument(doc);
      assertTrue( validator.getDocument() != null );
      assertTrue( validator.getModel() != null );
      assertTrue( validator.getErrorLog() != null );
      assertTrue( validator.getFailures().size() == 0 );
      assertTrue( validator.validate() == 0 );
    }

  }
}
