/*
 * @file    TestL3FormulaParserC.java
 * @brief   L3FormulaParser unit tests
 *
 * @author  Akiya Jouraku (Java conversion)
 * @author  Ben Bornstein 
 * 
 * ====== WARNING ===== WARNING ===== WARNING ===== WARNING ===== WARNING ======
 *
 * DO NOT EDIT THIS FILE.
 *
 * This file was generated automatically by converting the file located at
 * src/sbml/test/TestL3FormulaParserC.c
 * using the conversion program dev/utilities/translateTests/translateTests.pl.
 * Any changes made here will be lost the next time the file is regenerated.
 *
 * -----------------------------------------------------------------------------
 * This file is part of libSBML.  Please visit http://sbml.org for more
 * information about SBML, and the latest version of libSBML.
 *
 * Copyright 2005-2010 California Institute of Technology.
 * Copyright 2002-2005 California Institute of Technology and
 *                     Japan Science and Technology Corporation.
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation.  A copy of the license agreement is provided
 * in the file named "LICENSE.txt" included with this software distribution
 * and also available online as http://sbml.org/software/libsbml/license.html
 * -----------------------------------------------------------------------------
 */

package org.sbml.libsbml.test.math;

import org.sbml.libsbml.*;

import java.io.File;
import java.lang.AssertionError;

public class TestL3FormulaParserC {

  static void assertTrue(boolean condition) throws AssertionError
  {
    if (condition == true)
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertEquals(Object a, Object b) throws AssertionError
  {
    if ( (a == null) && (b == null) )
    {
      return;
    }
    else if ( (a == null) || (b == null) )
    {
      throw new AssertionError();
    }
    else if (a.equals(b))
    {
      return;
    }

    throw new AssertionError();
  }

  static void assertNotEquals(Object a, Object b) throws AssertionError
  {
    if ( (a == null) && (b == null) )
    {
      throw new AssertionError();
    }
    else if ( (a == null) || (b == null) )
    {
      return;
    }
    else if (a.equals(b))
    {
      throw new AssertionError();
    }
  }

  static void assertEquals(boolean a, boolean b) throws AssertionError
  {
    if ( a == b )
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertNotEquals(boolean a, boolean b) throws AssertionError
  {
    if ( a != b )
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertEquals(int a, int b) throws AssertionError
  {
    if ( a == b )
    {
      return;
    }
    throw new AssertionError();
  }

  static void assertNotEquals(int a, int b) throws AssertionError
  {
    if ( a != b )
    {
      return;
    }
    throw new AssertionError();
  }

  public void test_SBML_C_parseL3Formula_1()
  {
    ASTNode r = "1".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_INTEGER );
    assertTrue( r.getInteger() == 1 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_10()
  {
    ASTNode r = "1 + -2e100 / 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_PLUS );
    assertTrue( r.getCharacter() == '+' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_DIVIDE );
    assertTrue( c.getCharacter() == '/' );
    assertTrue( c.getNumChildren() == 2 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getCharacter() == '-' );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL_E );
    assertTrue( c.getMantissa() == 2 );
    assertTrue( c.getExponent() == 100 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_11()
  {
    ASTNode r = "1 - -foo / 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getCharacter() == '-' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_DIVIDE );
    assertTrue( c.getCharacter() == '/' );
    assertTrue( c.getNumChildren() == 2 );
    c = r.getRightChild().getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getCharacter() == '-' );
    assertTrue( c.getNumChildren() == 1 );
    c = r.getRightChild().getLeftChild().getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "foo"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_12()
  {
    ASTNode r = "2 * foo^bar + 3.0".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_PLUS );
    assertTrue( r.getCharacter() == '+' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_TIMES );
    assertTrue( c.getCharacter() == '*' );
    assertTrue( c.getNumChildren() == 2 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 3.0 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_POWER );
    assertTrue( c.getCharacter() == '^' );
    assertTrue( c.getNumChildren() == 2 );
    c = r.getLeftChild().getRightChild().getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "foo"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getRightChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "bar"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_13()
  {
    ASTNode r = "foo()".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_FUNCTION );
    assertTrue(r.getName().equals( "foo"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_14()
  {
    ASTNode r = "foo(1)".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_FUNCTION );
    assertTrue(r.getName().equals( "foo"));
    assertTrue( r.getNumChildren() == 1 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_15()
  {
    ASTNode r = "foo(1, bar)".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_FUNCTION );
    assertTrue(r.getName().equals( "foo"));
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "bar"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_16()
  {
    ASTNode r = "foo(1, bar, 2^-3)".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_FUNCTION );
    assertTrue(r.getName().equals( "foo"));
    assertTrue( r.getNumChildren() == 3 );
    c = r.getChild(0);
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getChild(1);
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "bar"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getChild(2);
    assertTrue( c.getType() == libsbml.AST_POWER );
    assertTrue( c.getCharacter() == '^' );
    assertTrue( c.getNumChildren() == 2 );
    c = r.getChild(2).getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getChild(2).getRightChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getCharacter() == '-' );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_17()
  {
    ASTNode r = "1//1".parseL3Formula();
    String error;
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input '1//1' at position 3:  syntax error, unexpected '/'"));
  }

  public void test_SBML_C_parseL3Formula_18()
  {
    ASTNode r = "1+2*3 4".parseL3Formula();
    String error;
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input '1+2*3 4' at position 7:  syntax error, unexpected integer"));
  }

  public void test_SBML_C_parseL3Formula_2()
  {
    ASTNode r = "2.1".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( r.getReal() == 2.1 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_3()
  {
    ASTNode r = "2.1e5".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL_E );
    assertTrue( r.getMantissa() == 2.1 );
    assertTrue( r.getExponent() == 5 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_4()
  {
    ASTNode r = "foo".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "foo"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_5()
  {
    ASTNode r = "1 + foo".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_PLUS );
    assertTrue( r.getCharacter() == '+' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "foo"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_6()
  {
    ASTNode r = "1 + 2".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_PLUS );
    assertTrue( r.getCharacter() == '+' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_7()
  {
    ASTNode r = "1 + 2 * 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_PLUS );
    assertTrue( r.getCharacter() == '+' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_TIMES );
    assertTrue( c.getCharacter() == '*' );
    assertTrue( c.getNumChildren() == 2 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_8()
  {
    ASTNode r = "(1 - 2) * 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_TIMES );
    assertTrue( r.getCharacter() == '*' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getCharacter() == '-' );
    assertTrue( c.getNumChildren() == 2 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_9()
  {
    ASTNode r = "1 + -2 / 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_PLUS );
    assertTrue( r.getCharacter() == '+' );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_DIVIDE );
    assertTrue( c.getCharacter() == '/' );
    assertTrue( c.getNumChildren() == 2 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getCharacter() == '-' );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_arguments()
  {
    String error;
    ASTNode r = "sin(x,y)".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'sin(x,y)' at position 8:  The function 'sin' takes exactly one argument, but 2 were found."));
    r = "delay(x)".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'delay(x)' at position 8:  The function 'delay' takes exactly two arguments, but 1 were found."));
    r = "piecewise()".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'piecewise()' at position 11:  The function 'piecewise' takes at least one argument, but none were found."));
    r = "gt(x)".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'gt(x)' at position 5:  The function 'gt' takes at least two arguments, but 1 were found."));
    r = "minus()".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'minus()' at position 7:  The function 'minus' takes exactly one or two arguments, but 0 were found."));
    r = "root(x, y, z)".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'root(x, y, z)' at position 13:  The function 'root' takes exactly one or two arguments, but 3 were found."));
    r = "power()".parseL3Formula();
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input 'power()' at position 7:  The function 'power' takes exactly two arguments, but 0 were found."));
  }

  public void test_SBML_C_parseL3Formula_avogadrosettings()
  {
    ASTNode r = "avogadro".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_NAME_AVOGADRO );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseAvogadroCsymbol(0);
    assertTrue( settings.getParseAvogadroCsymbol() == 0 );
    r = "avogadro".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "avogadro"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    settings.setParseAvogadroCsymbol(1);
    assertTrue( settings.getParseAvogadroCsymbol() == 1 );
    r = "avogadro".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_NAME_AVOGADRO );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_collapseminussettings1()
  {
    ASTNode r = "--4.4".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 1 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseCollapseMinus(1);
    assertTrue( settings.getParseCollapseMinus() == 1 );
    r = "--4.4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( r.getReal() == 4.4 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    settings.setParseCollapseMinus(0);
    assertTrue( settings.getParseCollapseMinus() == 0 );
    r = "--4.4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 1 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_collapseminussettings2()
  {
    ASTNode r = "--x".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 1 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseCollapseMinus(1);
    assertTrue( settings.getParseCollapseMinus() == 1 );
    r = "--x".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "x"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    settings.setParseCollapseMinus(0);
    assertTrue( settings.getParseCollapseMinus() == 0 );
    r = "--x".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 1 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_collapseminussettings3()
  {
    ASTNode r = "x---4.4".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseCollapseMinus(1);
    assertTrue( settings.getParseCollapseMinus() == 1 );
    r = "x---4.4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings.setParseCollapseMinus(0);
    assertTrue( settings.getParseCollapseMinus() == 0 );
    r = "x---4.4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_collapseminussettings4()
  {
    ASTNode r = "x---y".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "y"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseCollapseMinus(1);
    assertTrue( settings.getParseCollapseMinus() == 1 );
    r = "x---y".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "y"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings.setParseCollapseMinus(0);
    assertTrue( settings.getParseCollapseMinus() == 0 );
    r = "x---y".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_MINUS );
    assertTrue( c.getNumChildren() == 1 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "y"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_collapseminussettings5()
  {
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseCollapseMinus(1);
    assertTrue( settings.getParseCollapseMinus() == 1 );
    ASTNode r = "---4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_INTEGER );
    assertTrue( r.getInteger() == -4 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    r = "---(3/8)".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_RATIONAL );
    assertTrue( r.getNumerator() == -3 );
    assertTrue( r.getDenominator() == 8 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    r = "---(-3/8)".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_RATIONAL );
    assertTrue( r.getNumerator() == 3 );
    assertTrue( r.getDenominator() == 8 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    r = "---4.4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( r.getReal() == -4.4 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    r = "---4e-3".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_REAL_E );
    assertTrue( r.getMantissa() == -4 );
    assertTrue( r.getExponent() == -3 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    r = "---.4".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( r.getReal() == -.4 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_constants1()
  {
    ASTNode r = "true".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_CONSTANT_TRUE );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants10()
  {
    ASTNode r = "notanumber".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( util_isNaN == 1 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants11()
  {
    ASTNode r = "nan".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( util_isNaN == 1 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants12()
  {
    ASTNode r = "NaN".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( util_isNaN == 1 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants2()
  {
    ASTNode r = "false".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_CONSTANT_FALSE );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants3()
  {
    ASTNode r = "pi".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_CONSTANT_PI );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants4()
  {
    ASTNode r = "exponentiale".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_CONSTANT_E );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants5()
  {
    ASTNode r = "avogadro".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_NAME_AVOGADRO );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants6()
  {
    ASTNode r = "time".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_NAME_TIME );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants7()
  {
    ASTNode r = "inf".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( util_isInf(r.getReal()) == true );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants8()
  {
    ASTNode r = "infinity".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( util_isInf(r.getReal()) == true );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_constants9()
  {
    ASTNode r = "INF".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL );
    assertTrue( util_isInf(r.getReal()) == true );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_e1()
  {
    ASTNode r = "2.001e+5".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL_E );
    assertTrue( r.getMantissa() == 2.001 );
    assertTrue( r.getExponent() == 5 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_e2()
  {
    ASTNode r = ".001e+5".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL_E );
    assertTrue( r.getMantissa() == .001 );
    assertTrue( r.getExponent() == 5 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_e3()
  {
    ASTNode r = ".001e-5".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL_E );
    assertTrue( r.getMantissa() == .001 );
    assertTrue( r.getExponent() == -5 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_e4()
  {
    ASTNode r = "2.e-005".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_REAL_E );
    assertTrue( r.getMantissa() == 2 );
    assertTrue( r.getExponent() == -5 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_e5()
  {
    ASTNode r = ".e+5".parseL3Formula();
    String error;
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input '.e+5' at position 1:  syntax error, unexpected $undefined"));
    r = null;
  }

  public void test_SBML_C_parseL3Formula_logic1()
  {
    ASTNode r = "1 && 2 == 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_LOGICAL_AND );
    assertTrue(r.getName().equals( "and"));
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_RELATIONAL_EQ );
    assertTrue(c.getName().equals( "eq"));
    assertTrue( c.getNumChildren() == 2 );
    c = c.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_logic2()
  {
    ASTNode r = "(1 && 2) == 3".parseL3Formula();
    ASTNode c;
    assertTrue( r.getType() == libsbml.AST_RELATIONAL_EQ );
    assertTrue(r.getName().equals( "eq"));
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_LOGICAL_AND );
    assertTrue(c.getName().equals( "and"));
    assertTrue( c.getNumChildren() == 2 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getLeftChild().getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent1()
  {
    Model model = new  Model(3,1);
    Parameter p = model.createParameter();
    p.setId( "infinity");
    ASTNode r = "infinity".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "infinity"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent2()
  {
    Model model = new  Model(3,1);
    Species p = model.createSpecies();
    p.setId( "true");
    ASTNode r = "true".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "true"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent3()
  {
    Model model = new  Model(3,1);
    Compartment p = model.createCompartment();
    p.setId( "NaN");
    ASTNode r = "NaN".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "NaN"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent4()
  {
    Model model = new  Model(3,1);
    Reaction p = model.createReaction();
    p.setId( "pi");
    ASTNode r = "pi".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "pi"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent5()
  {
    Model model = new  Model(3,1);
    Reaction p = model.createReaction();
    SpeciesReference sr = p.createProduct();
    sr.setId( "avogadro");
    ASTNode r = "avogadro".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_NAME );
    assertTrue(r.getName().equals( "avogadro"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent6()
  {
    Model model = new  Model(3,1);
    Reaction p = model.createReaction();
    SpeciesReference sr = p.createProduct();
    sr.setId( "AVOGADRO");
    ASTNode r = "avogadro".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_NAME_AVOGADRO );
    assertTrue(r.getName().equals( "avogadro"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modelPresent7()
  {
    Model model = new  Model(3,1);
    FunctionDefinition p = model.createFunctionDefinition();
    p.setId( "sin");
    ASTNode r = "sin(x, y)".parseL3FormulaWithModel(model);
    assertTrue( r.getType() == libsbml.AST_FUNCTION );
    assertTrue(r.getName().equals( "sin"));
    assertTrue( r.getNumChildren() == 2 );
    r = null;
    model = null;
  }

  public void test_SBML_C_parseL3Formula_modulo()
  {
    ASTNode r = "x % y".parseL3Formula();
    String s = libsbml.formulaToString(r);
    assertTrue(s.equals( "piecewise(x - y * ceil(x / y), xor(lt(x, 0), lt(y, 0)), x - y * floor(x / y))"));
    r = null;
  }

  public void test_SBML_C_parseL3Formula_negInf()
  {
    ASTNode r = "-inf".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getCharacter() == '-' );
    assertTrue( r.getNumChildren() == 1 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( util_isInf(c.getReal()) == true );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_negZero()
  {
    ASTNode r = "-0.0".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_MINUS );
    assertTrue( r.getCharacter() == '-' );
    assertTrue( r.getNumChildren() == 1 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( util_isNegZero == 0 );
    assertTrue( c.getReal() == 0 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_oddMathML1()
  {
    ASTNode r = "sqrt(3)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_FUNCTION_ROOT );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_oddMathML2()
  {
    ASTNode r = "sqr(3)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_FUNCTION_POWER );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 2 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_oddMathML3()
  {
    ASTNode r = "log10(3)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_FUNCTION_LOG );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 10 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_oddMathML4()
  {
    ASTNode r = "log(4.4, 3)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_FUNCTION_LOG );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_oddMathML5()
  {
    ASTNode r = "root(1.1, 3)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_FUNCTION_ROOT );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 1.1 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_parselogsettings()
  {
    ASTNode r = "log(4.4)".parseL3Formula();
    ASTNode c;
    String error;
    assertTrue( r.getType() == libsbml.AST_FUNCTION_LOG );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 10 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = new  L3ParserSettings();
    settings.setParseLog(L3P_PARSE_LOG_AS_LN);
    assertTrue( settings.getParseLog().equals(L3P_PARSE_LOG_AS_LN) );
    r = "log(4.4)".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_FUNCTION_LN );
    assertTrue( r.getNumChildren() == 1 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings.setParseLog(L3P_PARSE_LOG_AS_LOG10);
    assertTrue( settings.getParseLog().equals(L3P_PARSE_LOG_AS_LOG10) );
    r = "log(4.4)".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_FUNCTION_LOG );
    assertTrue( r.getNumChildren() == 2 );
    c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 10 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
    settings.setParseLog(L3P_PARSE_LOG_AS_ERROR);
    assertTrue( settings.getParseLog().equals(L3P_PARSE_LOG_AS_ERROR) );
    r = "log(4.4)".parseL3FormulaWithSettings(settings);
    error = .getLastParseL3Error();
    assertTrue( r == null );
    assertTrue(error.equals( "Error when parsing input 'log(4.4)' at position 8:  Writing a function as 'log(x)' was legal in the L1 parser, but translated as the natural log, not the base-10 log.  This construct is disallowed entirely as being ambiguous, and you are encouraged instead to use 'ln(x)', 'log10(x)', or 'log(base, x)'."));
    settings = null;
  }

  public void test_SBML_C_parseL3Formula_precedence()
  {
    ASTNode root = "a && b == !(c - d * e^-f) ".parseL3Formula();
    ASTNode left;
    ASTNode right;
    assertTrue( root.getType() == libsbml.AST_LOGICAL_AND );
    assertTrue(root.getName().equals( "and"));
    assertTrue( root.getNumChildren() == 2 );
    left = root.getLeftChild();
    assertTrue( left.getType() == libsbml.AST_NAME );
    assertTrue(left.getName().equals( "a"));
    assertTrue( left.getNumChildren() == 0 );
    right = root.getRightChild();
    assertTrue( right.getType() == libsbml.AST_RELATIONAL_EQ );
    assertTrue(right.getName().equals( "eq"));
    assertTrue( right.getNumChildren() == 2 );
    left = right.getLeftChild();
    assertTrue( left.getType() == libsbml.AST_NAME );
    assertTrue(left.getName().equals( "b"));
    assertTrue( left.getNumChildren() == 0 );
    right = right.getRightChild();
    assertTrue( right.getType() == libsbml.AST_LOGICAL_NOT );
    assertTrue(right.getName().equals( "not"));
    assertTrue( right.getNumChildren() == 1 );
    right = right.getLeftChild();
    assertTrue( right.getType() == libsbml.AST_MINUS );
    assertTrue( right.getCharacter() == '-' );
    assertTrue( right.getNumChildren() == 2 );
    left = right.getLeftChild();
    assertTrue( left.getType() == libsbml.AST_NAME );
    assertTrue(left.getName().equals( "c"));
    assertTrue( left.getNumChildren() == 0 );
    right = right.getRightChild();
    assertTrue( right.getType() == libsbml.AST_TIMES );
    assertTrue( right.getCharacter() == '*' );
    assertTrue( right.getNumChildren() == 2 );
    left = right.getLeftChild();
    assertTrue( left.getType() == libsbml.AST_NAME );
    assertTrue(left.getName().equals( "d"));
    assertTrue( left.getNumChildren() == 0 );
    right = right.getRightChild();
    assertTrue( right.getType() == libsbml.AST_POWER );
    assertTrue( right.getCharacter() == '^' );
    assertTrue( right.getNumChildren() == 2 );
    left = right.getLeftChild();
    assertTrue( left.getType() == libsbml.AST_NAME );
    assertTrue(left.getName().equals( "e"));
    assertTrue( left.getNumChildren() == 0 );
    right = right.getRightChild();
    assertTrue( right.getType() == libsbml.AST_MINUS );
    assertTrue( right.getCharacter() == '-' );
    assertTrue( right.getNumChildren() == 1 );
    left = right.getLeftChild();
    assertTrue( left.getType() == libsbml.AST_NAME );
    assertTrue(left.getName().equals( "f"));
    assertTrue( left.getNumChildren() == 0 );
    root = null;
  }

  public void test_SBML_C_parseL3Formula_rational1()
  {
    ASTNode r = "(3/4)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_RATIONAL );
    assertTrue( r.getNumerator() == 3 );
    assertTrue( r.getDenominator() == 4 );
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_rational2()
  {
    ASTNode r = "(3/4) mL".parseL3Formula();
    String units = r.getUnits();
    assertTrue( r.getType() == libsbml.AST_RATIONAL );
    assertTrue( r.getNumerator() == 3 );
    assertTrue( r.getDenominator() == 4 );
    assertTrue(units.equals( "mL"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_rational3()
  {
    ASTNode r = "3/4".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_DIVIDE );
    assertTrue( r.getCharacter() == '/' );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_rational4()
  {
    ASTNode r = "(3/x)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_DIVIDE );
    assertTrue( r.getCharacter() == '/' );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_NAME );
    assertTrue(c.getName().equals( "x"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_rational5()
  {
    ASTNode r = "(3/4.4)".parseL3Formula();
    assertTrue( r.getType() == libsbml.AST_DIVIDE );
    assertTrue( r.getCharacter() == '/' );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    assertTrue( c.getType() == libsbml.AST_REAL );
    assertTrue( c.getReal() == 4.4 );
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_rational6()
  {
    ASTNode r = "3/4 ml".parseL3Formula();
    String units;
    assertTrue( r.getType() == libsbml.AST_DIVIDE );
    assertTrue( r.getCharacter() == '/' );
    assertTrue( r.getNumChildren() == 2 );
    ASTNode c = r.getLeftChild();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 3 );
    assertTrue( c.getNumChildren() == 0 );
    c = r.getRightChild();
    units = c.getUnits();
    assertTrue( c.getType() == libsbml.AST_INTEGER );
    assertTrue( c.getInteger() == 4 );
    assertTrue(units.equals( "ml"));
    assertTrue( c.getNumChildren() == 0 );
    r = null;
  }

  public void test_SBML_C_parseL3Formula_rational7()
  {
    ASTNode r = "(3/4.4) ml".parseL3Formula();
    String error;
    assertTrue( r == null );
    error = .getLastParseL3Error();
    assertTrue(error.equals( "Error when parsing input '(3/4.4) ml' at position 10:  syntax error, unexpected element name"));
  }

  public void test_SBML_C_parseL3Formula_unitssettings()
  {
    ASTNode r = "4 mL".parseL3Formula();
    String error;
    String units;
    assertTrue( r.getType() == libsbml.AST_INTEGER );
    assertTrue( r.getInteger() == 4 );
    units = r.getUnits();
    assertTrue(units.equals( "mL"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    L3ParserSettings settings = .getDefaultL3ParserSettings();
    settings.setParseUnits(0);
    assertTrue( settings.getParseUnits() == 0 );
    r = "4 mL".parseL3FormulaWithSettings(settings);
    error = .getLastParseL3Error();
    assertTrue( r == null );
    assertTrue(error.equals( "Error when parsing input '4 mL' at position 4:  The ability to associate units with numbers has been disabled."));
    settings.setParseUnits(1);
    assertTrue( settings.getParseUnits() == 1 );
    r = "4 mL".parseL3FormulaWithSettings(settings);
    assertTrue( r.getType() == libsbml.AST_INTEGER );
    assertTrue( r.getInteger() == 4 );
    units = r.getUnits();
    assertTrue(units.equals( "mL"));
    assertTrue( r.getNumChildren() == 0 );
    r = null;
    settings = null;
  }

  /**
   * Loads the SWIG-generated libSBML Java module when this class is
   * loaded, or reports a sensible diagnostic message about why it failed.
   */
  static
  {
    String varname;
    String shlibname;

    if (System.getProperty("mrj.version") != null)
    {
      varname = "DYLD_LIBRARY_PATH";    // We're on a Mac.
      shlibname = "libsbmlj.jnilib and/or libsbml.dylib";
    }
    else
    {
      varname = "LD_LIBRARY_PATH";      // We're not on a Mac.
      shlibname = "libsbmlj.so and/or libsbml.so";
    }

    try
    {
      System.loadLibrary("sbmlj");
      // For extra safety, check that the jar file is in the classpath.
      Class.forName("org.sbml.libsbml.libsbml");
    }
    catch (SecurityException e)
    {
      e.printStackTrace();
      System.err.println("Could not load the libSBML library files due to a"+
                         " security exception.\n");
      System.exit(1);
    }
    catch (UnsatisfiedLinkError e)
    {
      e.printStackTrace();
      System.err.println("Error: could not link with the libSBML library files."+
                         " It is likely\nyour " + varname +
                         " environment variable does not include the directories\n"+
                         "containing the " + shlibname + " library files.\n");
      System.exit(1);
    }
    catch (ClassNotFoundException e)
    {
      e.printStackTrace();
      System.err.println("Error: unable to load the file libsbmlj.jar."+
                         " It is likely\nyour -classpath option and CLASSPATH" +
                         " environment variable\n"+
                         "do not include the path to libsbmlj.jar.\n");
      System.exit(1);
    }
  }
}
